services: 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NETFLIX_EMAIL=${NETFLIX_EMAIL}
      - NETFLIX_PASSWORD=${NETFLIX_PASSWORD}
      - DISNEY_EMAIL=${DISNEY_EMAIL}
      - DISNEY_PASSWORD=${DISNEY_PASSWORD}
      - IMAP_SERVER=${IMAP_SERVER}